// Development dataset: 180 synthetic vehicles generated by scripts/vehicles/generate.mjs.
// Makes, models and versions are real; prices, mileage, stock and evidence are not.
// See data/vehicles/README.md before changing anything here.
import data from './vehicles.json';

export type BodyType = 'hatch' | 'sedan' | 'suv' | 'pickup' | 'minivan' | 'coupe';
export type Fuel = 'flex' | 'gasoline' | 'diesel' | 'hybrid' | 'electric';
export type Transmission = 'automatic' | 'manual';
export type Color = 'white' | 'silver' | 'gray' | 'black' | 'red' | 'blue' | 'brown' | 'green' | 'beige';

export type Evidence =
  | { type: 'warranty'; kind: 'factory'; until: string }
  | { type: 'inspection'; result: 'approved' }
  | { type: 'serviceHistory'; services: number }
  | { type: 'singleOwner' }
  // No auction, total loss or theft record.
  | { type: 'cleanHistory' };

export type MediaItem = {
  src: string;
  credit?: { author: string; license: string; licenseUrl: string; source: string };
};

export type Store = { id: string; name: string };

export type Vehicle = {
  id: string;
  make: string;
  model: string;
  trim: string;
  version: string;
  year: number;
  bodyType: BodyType;
  fuel?: Fuel;
  transmission?: Transmission;
  km?: number;
  color?: Color;
  doors?: number;
  price: number;
  fipe?: { value: number; code: string; referenceMonth: string };
  storeId: string;
  listedAt: string;
  media: MediaItem[];
  evidence: Evidence[];
  // Which evidence the listing card shows, chosen per vehicle in the data. Only types
  // with copy in the design: single owner and clean history are not shown in the UI yet.
  featuredEvidence?: 'warranty' | 'inspection' | 'serviceHistory';
  ipvaPaidYear?: number;
  features?: string[];
};

type Dataset = { referenceDate: string; stores: Store[]; vehicles: Vehicle[] };

const dataset = data as Dataset;

export const referenceDate = dataset.referenceDate;
export const stores = dataset.stores;
export const vehicles = dataset.vehicles;
